site_name: Lanes Arabic-English Lexicon
pages:
- Welcome: 'index.md'
- User Guide:
  - 'Introduction': 'user-guide/using.md'
  - 'Configuration' : 'user-guide/configuring.md'
  - 'Bookmarks' : 'user-guide/bookmarks.md'
  - 'Searching' : 'user-guide/search.md'
  - 'Customization' : 'user-guide/custom.md'
  - 'Obtaining' : 'download.md'
- Technical Guide:
  - 'Building' : 'dev-guide/build.md'
- About:
  - 'License' : 'about/license.md'
- Lanes Preface:
  - 'Preface' : 'lane/preface.md'
  - 'Notice'  : 'lane/notice.md'
  - 'Postscript to the Preface': 'lane/postscript.md'




theme: readthedocs
