site_name: Lanes Lexicon
pages:
- ['index.md', Welcome]
- ['user-guide/using.md', User Guide, 'Introduction']
- ['user-guide/configuring.md', User Guide, 'Configuration']
- ['user-guide/bookmarks.md', User Guide, 'Bookmarks']
- ['user-guide/search.md', User Guide, 'Searching']
- ['user-guide/custom.md', User Guide, 'Customization']
- ['dev-guide/build.md', Development, 'Building']
- ['lane/preface.md','Lane','Preface']
- ['lane/notice.md','Lane','Notice']
- ['lane/postscript.md','Lane','Postscript to the Preface']
- ['download.md', Download]
- ['build.md', 'Building', 'Building']
- ['about/license.md', 'About', 'License']
theme: readthedocs
