site_name: Lane's Arabic-English Lexicon
pages:
- Welcome: 'index.md'
- Introduction:
  - 'Background'  : 'introduction/intro.md'
  - 'Quick start' : 'introduction/start.md'
- 'User Guide':
  - Appearance : user-guide/docking.md
  - Contents   : user-guide/contents.md
  - Entry : user-guide/moving.md
  - Tabs     : user-guide/tabs.md
  - Searching : 'user-guide/search.md'
  - Entering Arabic text : user-guide/entering.md
  - Bookmarks : 'user-guide/bookmarks.md'
  - History : user-guide/history.md
  - Saving state : 'user-guide/tabsets.md'
  - Notes : 'user-guide/notes.md'
  - Cross references : 'user-guide/missinglinks.md'
  - Some differences : 'user-guide/diffs.md'
- Customization :
  - Introduction : custom/custom.md
  - Themes : 'custom/themes.md'
  - Changing fonts : 'custom/font.md'
  - Using Edit View   : 'custom/editview.md'
#  - Shortcuts          : 'custom/shortcuts.md'
#  - Keymaps            : 'custom/keymaps.md'
- Options :
  - Introduction : 'options/options_intro.md'
  - System : 'options/options_system.md'
  - Contents :  options/options_contents.md
  - Printer : 'options/options_printer.md'
  - Diacritics : options/options_diacritics.md
  - Shortcuts  : options/options_shortcuts.md
  - Entry      : options/options_entry.md
  - Search      : options/options_search.md
  - Bookmarks      : options/options_bookmarks.md
  - Logging     : options/options_logging.md
  - History     : options/options_history.md
  - Icons       : options/options_icons.md
  - Arabic CSS  : options/options_spanned.md
- Other :
  - Editing the text : 'other/editing.md'
  - Word order      : 'other/orths.md'
  - Reporting errors : 'other/errors.md'
  - The CSS structure of an entry : other/entrycss.md
  - The XML structure of an entry : other/entryxml.md
  - Updating the Lexicon : other/dbupdate.md
#- Sharing : sharing.md
- Obtaining : obtaining.md
- Contact : contact.md
- Technical Guide:
  - 'Building' : 'dev-guide/build.md'
  - 'Virtual keyboards' : 'dev-guide/vkeyboard.md'
  - Setting up a keymap : dev-guide/keymaps.md
  - Scripts : dev-guide/scripts.md
- About:
  - 'License' : 'about/license.md'
  - 'Acknowledgments' : 'about/acknowledgements.md'
- Lane's Preface:
  - Note : 'lane/note.md'
  - 'Preface' : 'lane/preface.md'
  - 'Notice'  : 'lane/notice.md'
  - 'Postscript to the Preface': 'lane/postscript.md'
- '' : 404.md
- Appendix:
  - Buckwalter transliteration : 'other/buckwalter.md'
  - Buckwalter keymap : appendix/buckwalterkeymap.md
  - Windows 101 text specification : appendix/windows101_text.md
  - Windows 101 INI specification : appendix/windows101_ini.md




theme: readthedocs
